name: bull
description: A collection of convenient and useful Command-Line interfaces for development.
version: 0.0.4
homepage: https://github.com/dev-yakuza/bull
repository: https://github.com/dev-yakuza/bull

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  args: ^2.4.1

dev_dependencies:
  lints: ^2.0.0
  run_with_print: ^0.0.1
  test: ^1.21.0
